# Generated by Django 4.2.2 on 2023-12-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/R.e826020767e491f4054f6fcfd6d44222?rik=Fs2Mp4uA96SBRw&riu=http%3a%2f%2fwww.fnasafety.com%2fwp-content%2fuploads%2f2016%2f04%2fComingSoon2-fnasafety.png&ehk=qk9WvOpnJXmBGGVNzXXCziDdKvkr5eyyukPFh2SdZe4%3d&risl=&pid=ImgRaw&r=0', max_length=500),
        ),
    ]
