# Generated by Django 4.2.7 on 2023-12-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas ad quos, aliquid enim omnis expedita porro aut exercitationem adipisci id perspiciatis fugiat consectetur aliquam consequuntur sapiente hic vitae unde! Possimus.', max_length=500),
        ),
    ]
